name: Make QuizMaster installable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Set up virtual environment
        run: |
          python -m venv venv
          if [ $RUNNER_OS == 'Linux' ]; then
            echo "Activating virtual environment on Linux"
            source venv/bin/activate
          else
            echo "Activating virtual environment on Windows"
            venv\Scripts\activate
          fi

      - name: Install tkinter (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get install python3-tk

      - name: Install dependencies
        run: |
          if [ $RUNNER_OS == 'Linux' ]; then
            source venv/bin/activate
          else
            venv\Scripts\activate
          fi
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          if [ $RUNNER_OS == 'Linux' ]; then
            source venv/bin/activate
          else
            venv\Scripts\activate
          fi
          pytest

  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Set up virtual environment
        run: |
          python -m venv venv
          if [ $RUNNER_OS == 'Linux' ]; then
            echo "Activating virtual environment on Linux"
            source venv/bin/activate
          else
            echo "Activating virtual environment on Windows"
            venv\Scripts\activate
          fi

      - name: Install tkinter (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get install python3-tk

      - name: Install dependencies
        run: |
          if [ $RUNNER_OS == 'Linux' ]; then
            source venv/bin/activate
          else
            venv\Scripts\activate
          fi
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Executable
        run: |
          if [ $RUNNER_OS == 'Linux' ]; then
            source venv/bin/activate
          else
            venv\Scripts\activate
          fi
          pyinstaller --onefile --name "QuizMaster" --windowed build.spec

permissions:
  contents: read
  actions: write
