name: Make QuizMaster installable

on:
  push: 
    - branches: [main]
  pull_request:
    - branches: [main]

jobs:
  pyinstaller-build:
    runs-on: <windows-latest / ubuntu-latest>
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'My executable'
          options: --onefile, --name "QuizMaster", --windowed, 
